### ISSUE TITLE
not showing Fraction line

### ISSUE THREAD

**Issue by eliteluxury** [garciparedes/ng-katex#115]
I tried to display fractions but it shows like this.

![screenshot-localhost-4200-2018 03 08-07-56-50](https://user-images.githubusercontent.com/35144713/37132253-5b333d22-22a6-11e8-8b0d-7b476e83067a.png)

The line between fractions isn't displayed.
Please give some advice for this.

**Comment by garciparedes** [comment]
Hi @eliteluxury! Can you share a minimal reproducible example of this issue on [Plunker](https://plnkr.co/) or something like that? Many thanks for notify this issue. 🙂

**Comment by eliteluxury** [comment]
I put them into array and simply displayed them.

fractions = [ "\frac{1}{6}", "\frac{1}{4}", "\frac{1}{3}","\frac{1}{2}" ];

<div *ngFor="let fraction of fractions">
      <ng-katex [equation] = "fraction"></ng-katex>
</div>

**Comment by garciparedes** [comment]
Maybe your issue comes from KaTeX css version. Can you check if the bad redering continues when you use `0.9.0` version? I.e. `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css">`
