### ISSUE TITLE
KatexModule is not an NgModule

### ISSUE THREAD

**Issue by BOb511** [garciparedes/ng-katex#17]
I am getting this error when trying to start the dev Server fresh with `ng serve`. Oddly enough it works if it's already running and I just add it as a module afterwards.
Version: v0.3.21

So I tried with v0.3.30 and got another error:
`ERROR in Error: Metadata version mismatch for module ./node_modules/ng-katex/ng-katex.d.ts, found version 4, expected 3, resolving symbol ...`

I am on Angular 4.3.6.

Any idea?

Thanks for the project, looking good!

**Comment by garciparedes** [comment]
Hi @BOb511, 

There was an error related with the Angular version (5.0.1) used to compile de `ng-katex` module. In `v0.3.34` I fixed this bug, so the problem should be removed by installing that version.

The release changes are in https://github.com/garciparedes/ng-katex/commit/7cb3fc288678d8332db568db5cee264dd80bdffa and the release is https://github.com/garciparedes/ng-katex/releases/tag/v0.3.34, that you can install by:
```
npm install --save ng-katex@0.3.34
```

**Comment by garciparedes** [comment]
Many thanks for the feedback @BOb511 🙂. 
It's my first open source Angular module, so I accept any change recommendation.
