### ISSUE TITLE
IE11 Support?

### ISSUE THREAD

**Issue by BOb511** [garciparedes/ng-katex#19]
KaTeX supports IE9-11 but either ng-katex doesn't or I forgot something? Polyfills?
`ERROR TypeError: The object doesn't support the property or method "createShadowRoot` (roughly translated).
Btw the demo doesn't start at all on IE11. (different error though)

**Comment by garciparedes** [comment]
The problem is related with the `ViewEncapsulation` field according to 
https://github.com/angular/angular/issues/6531. You can solve it loading polyfills according to http://webcomponents.org/polyfills/

**Comment by garciparedes** [comment]
Hi @BOb511, this bug was fixed in `ng-katex@0.3.37`, so now you can use this Module without polyfills
