### ISSUE TITLE
Some equation can not been shown in right way with ionic framework.

### ISSUE THREAD

**Issue by ionicview** [garciparedes/ng-katex#210]
Hi,
When I use ng-katex  in ionic framework  some equation can not been displayed in the right way. 
For example,   x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a} .
It can be shown in Angular project normally ,but in ionic project  the position of b^2 is out of sqrt mark.
Can  ng-katex be used in ionic project? 

Any advice will be appreciate .
Thanks a lot .

**Comment by garciparedes** [comment]
Hi @ionicview!
Your problem is could be related with the @katex `css` loading. I suggest you to check that.

**Comment by ionicview** [comment]
Hi  garciparedes
Thank you very much for your replay!  After two week's work for my project , I  still  can not make it woks fine.
 
It looks like below.

![wechatimg4](https://user-images.githubusercontent.com/28757365/42412345-c8a6273a-8245-11e8-8058-f9c91f0de0b2.png)


How ever  ,if there is no divide operation in equation ,every thing look well.
![wechatimg6](https://user-images.githubusercontent.com/28757365/42412374-2415666c-8246-11e8-8d33-50cd6c2b45ef.png)

I load my css in this way and  I have no customer CSS in my project. Is there any thing wrong with css loading?
`  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.8.3/katex.min.css">`

By the way , is it possible that display not only equation but also Latex format text? For example,

```
equation = 'When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
  $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$ '
<ng-katex [equation]="equation" [options]="options"></ng-katex>
```

I hope it will display as below.
<img width="814" alt="2018-07-08 0 41 30" src="https://user-images.githubusercontent.com/28757365/42412464-bda07c58-8247-11e8-9462-d87a2493ba94.png">

But in fact , I got nothing to displayed.

Thanks a lot .

**Comment by garciparedes** [comment]
Hi @ionicview! Maybe your issue comes from KaTeX css version. Can you check if the bad redering continues when you use `0.9.0` version? I.e. `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css">`

About the text capabilities, I'm working on `<ng-katex-paragraph>`, which will implement that behavior. You can check issue #22 to know more about that.

**Comment by ionicview** [comment]
Hi @garciparedes!

With css version of 0.9.0 every thing looks perfect !!
Thank you very much .
You saved my time .

<ng-katex-paragraph> will be a great feature .
I  will check issue #22 every day .
ng-katex is so fast than mathjax .
Thank you  for your great works.
