### ISSUE TITLE
Implement "auto-parser" paragraph

### ISSUE THREAD

**Issue by garciparedes** [garciparedes/ng-katex#22]
The new component should receive an string (as parameter or by `<ng-content>`) and then, it should render all expressions delimited by `$` symbol, like in Tex language

**Comment by vahekilamyan** [comment]
Hi Sergio,

Using this library and that would be a great feature! 

<ng-katex [equation]="equation"></ng-katex>

equation = 'Some plain text: $//sum_{i=1}^nx_i$'; // Should render only the things in $ signs and math

Likewise,

equation = 'Some plain text: $$//sum_{i=1}^nx_i$$'; // Same, but should set "displayMode: true"

**Comment by garciparedes** [comment]
Hi @vahekilamyan,

Many thanks for the recommendation about the behaviour of the new feature. I'm planning to implement it during the christmas holidays, but if you want these feature right now pull requests are welcome.

**Comment by jondea** [comment]
Any update on your progress @garciparedes?

**Comment by garciparedes** [comment]
Many thanks to remember me this issue @jondea, I will start to work on it right now 🙂

**Comment by garciparedes** [comment]
The regex to extract equations should be `(\$[^\$]+\$)|(\$\$[^\$]+\$\$)`  matching Group 1 the normal case and Group 2 the displayMode case.

The regex can be tested here: https://regex101.com/r/J4sQXm/2

**Comment by jondea** [comment]
Great work by the way! 

It would appear that MathJax solves this problem by discouraging the use of single dollar sign delimiters:
([MathJax docs](http://docs.mathjax.org/en/latest/start.html#tex-and-latex-input)) 
> The default math delimiters are $$...$$ and \[...\] for displayed mathematics, and \(...\) for in-line mathematics. Note in particular that the $...$ in-line delimiters are not used by default. That is because dollar signs appear too often in non-mathematical settings, which could cause some text to be treated as mathematics unexpectedly. For example, with single-dollar delimiters, “… the cost is $2.50 for the first one, and $2.00 for each additional one …” would cause the phrase “2.50 for the first one, and” to be treated as mathematics since it falls between dollar signs.

It may be worth having an option to choose the delimiters (even if the choice is restricted) and choosing the same default.

**Comment by jondea** [comment]
I'm a little confused, I was about to fork the repo to add options for different delimiters but noticed that the paragraph component has disappeared on the master branch. My git knowledge is limited but it appears to be there in ddd8d70 but disappears in a4b6873. Any ideas on how this can happen?

**Comment by garciparedes** [comment]
`NgKatexParagraphComponent` is on [`issue-22`](https://github.com/garciparedes/ng-katex/tree/issue-22) branch. The reason it appears as deletion on `master` branch is due to a merge conflict. You can see the source code on https://github.com/garciparedes/ng-katex/blob/issue-22/src/ng-katex-paragraph.component.ts Maybe the code isn't as clear as it should be. I will improve soon.

**Comment by mist3r3** [comment]
Hey I'm also really interested in this. Is it possible to just merge the code from issue 22 to master? Anyways I guess we can just copy/paste the file  https://github.com/garciparedes/ng-katex/blob/issue-22/src/ng-katex-paragraph.component.ts to our own app right?

Thanks.

**Comment by garciparedes** [comment]
Hi @mist3r3 Let me to check this branch in a few days, and think on a solution to merge it without making bugs in `ng-katex`. I'm planning to publish a new version this weekend because many dependencies can be update!

**Comment by garciparedes** [comment]
Hi @mist3r3! I I have just implemented the code to scape the `$` symbol outside equations of paragraph. I implemented this using the `\$` from LaTeX. You can see the code [here](https://github.com/garciparedes/ng-katex/blob/issue-22/src/ng-katex-paragraph.component.ts). As you can see, the regex vars are truly illegible. Does someone know how to match groups by name?

**Comment by evanlegamer** [comment]
Hi @garciparedes, I just wanted to know where you are in the implementation of your features ? How can we use it and when will it be integrated into the master branch ? I am very interested in this feature so I can use katex in my project instead of mathjax. Thank you in Advance for your answer 👍

**Comment by colasbd** [comment]
Any news about this issue? Really interested by ANY solution!

**Comment by genebustam** [comment]
Is is possible to at least access the [window.renderMathInElement()](https://katex.org/docs/autorender.html) function from within angular components? I noticed that this module already has the `auto-render.js` script included. So... Whats the problem?

**Comment by garciparedes** [comment]
Hi everyone! The `katex-paragraph` it's implemented right now. Did anyone want to check if it works properly? 

To help me, it's necessary to clone `issue-22` branch on your desktop, open `docs/index.html` with your favourite browser and check if it's work like expected. Many thanks for your help!

**Comment by ionicview** [comment]
Hi @garciparedes,
  I 'd like to check if it is work as my expected . How to use katex-paragraph? Where can I get it?
 Thanks a lot .

**Comment by pnagendra540** [comment]
Yeah @garciparedes Its working properly. How to use this in my application? Thank you very much for your work.

**Comment by ionicview** [comment]
Hi , @garciparedes  It works just like I expected. Thank you for your great work.
When can I use it in my project?

**Comment by garciparedes** [comment]
Hi @ionicview, I'm planning to release a new version this week. I'm updating all dependencies and the I'll release it.

**Comment by garciparedes** [comment]
There're problems in non-Chrome browsers...

**Comment by garciparedes** [comment]
I've found the bug reason: https://stackoverflow.com/a/50434875/3921457

**Comment by garciparedes** [comment]
Hi Everyone! I need help with a JS Regular Expressions trouble. In words, I have the new regex to match non escaped dollars:
``` ts
private readonly boundary: RegExp =  /(?<!\\)\$/;
```
But the problem is that it's a Negative LookBehind technique, which is only implemented in newest Javascript processors. So I need to write that expression using standard techniques. Does someone help me?

**Comment by evanlegamer** [comment]
Hi guys, maybe i'm not the only one in this case, so i ask it here, how can i implement the latest feature "ng-katex-paragraph" in my project ?

 I tried first to download the master branch with npm but in fact this branch is not up to date. 

Then I tried to download this branch to copy it but only the compiled version in the folder "doc" works. So i put the src folder of this branch into my ng-katex/src folder in my project but the ng-katex-paragraph directive do not exist... 

Do you have an hint to make it works ? Thank you in advance for your help :)

**Comment by garciparedes** [comment]
Hi @evanlegamer, the issue comes from regex syntax implementation on non-Chrome browsers. I explained that problem few comments ago. I can't release this feature until the bug is solved.

**Comment by evanlegamer** [comment]
Okay @garciparedes, i tried some stuff, is this correct for you ?

`private readonly boundary: RegExp = ([^\\]|^)(\$);`

[Here is the link](https://regex101.com/r/7cd5xw/2) for the live example

**Comment by evanlegamer** [comment]
Hi, @garciparedes , Does my regex solve the problem or it's not what you wanted?

**Comment by caph1993** [comment]
Hi, I think @evanlegamer is correct. Moreover, since the first group of the expression is not of interest, you could use `?:` in the first group to avoid capturing it, like this:

`private readonly boundary: RegExp = (?:[^\\]|^)(\$);`

Alternatively, you could match the whole expression with `^\$|[^\\]\$` and get the last index of each match.

**Comment by evanlegamer** [comment]
Hi @garciparedes, Is there another bug? Can we put this branch in master?

**Comment by garciparedes** [comment]
Hi @evanlegamer, you can fork the repo, modify this branch and then make a Pull Request to this branch. I'm sorry to say that now I don't have enough time to solve it myself now, but any Pull Request on this project is welcome. 😉

**Comment by vberlier** [comment]
Hello! I created [extract-math](https://github.com/vberlier/extract-math) to isolate the parsing problem into a separate package. This makes it really easy to implement the `ng-katex-paragraph` component:

```ts
import { Component, Input } from '@angular/core'
import { extractMath, Segment } from 'extract-math'

@Component({
  selector: 'ng-katex-paragraph',
  template: `
    <p>
      <ng-container *ngFor="let segment of segments">
        <ng-katex
          *ngIf="segment.math else text"
          [equation]="segment.value"
          [options]="{ displayMode: segment.type === 'display' }">
        </ng-katex>
        <ng-template #text>{{ segment.value }}</ng-template>
      </ng-container>
    </p>
  `
})
export class KatexParagraphComponent {
  @Input() paragraph: string

  get segments (): Segment[] {
    return extractMath(this.paragraph)
  }
}
```

In case you're concerned about the additional dependency, [extract-math](https://github.com/vberlier/extract-math) is really small, doesn't use any regex lookahead or lookbehind, and works in every browser.

**Comment by garciparedes** [comment]
Hi @vberlier! Your library looks awesome! Can you make a pull request to the `issue-22` branch to include it in `ng-katex`?

**Comment by vberlier** [comment]
Sure #394

**Comment by garciparedes** [comment]
Thank you so much @vberlier! I'll verify the pull request today and if every think it's okay, I'll release a new `ng-katex` version before next Monday.

**Comment by garciparedes** [comment]
Hi @vberlier. I found one thing to improve in the `extract-math` library. When I write inline equations like `$45\$$`, that is  can't scape the scape the dollar symbol inside the equation. Nevertheless, I'll release a new `ng-katex` version today. Also, I'll create an issue in your project and when you it I'll update this dependency. 😉

**Comment by garciparedes** [comment]
The issue is https://github.com/vberlier/extract-math/issues/1

**Comment by vberlier** [comment]
I added a `raw` property to the extracted segments to make the integration with KaTeX more ergonomic. I made a pull request which uses `.raw` instead of `.value` for displaying the equations in the `ng-katex-paragraph` component #398.
