### ISSUE TITLE
For what we can use 'KatexDirective' directive?

### ISSUE THREAD

**Issue by KostyaTretyak** [garciparedes/ng-katex#27]
In source code, I see that there is [KatexDirective](https://github.com/garciparedes/ng-katex/blob/master/src/ng-katex.directive.ts) directive. At the moment, this is probably superfluous, right?

**Comment by KostyaTretyak** [comment]
Oh, I've already seen.

**Comment by garciparedes** [comment]
Hi @KostyaTretyak, I don't understand your  question. Can you explain more?

**Comment by KostyaTretyak** [comment]
For your module `ng-katex`, directive `KatexDirective` is superfluous. You can deal with only `KatexComponent` component.
