### ISSUE TITLE
Fonts issue

### ISSUE THREAD

**Issue by lazarljubenovic** [garciparedes/ng-katex#30]
When trying to use this as documentation suggests, I'm getting errors about missing fonts.

![image](https://user-images.githubusercontent.com/7661457/35182311-49ce312a-fdd2-11e7-9df4-96268701fa7f.png)

It's unclear how to proceed.

**Comment by lazarljubenovic** [comment]
With default CLI structure, I can add fonts folder and download the needed one from KaTeX official repo, but they have to be placed in `/assets/fonts`, not `/fonts`. How do I change the path to fonts?

**Comment by garciparedes** [comment]
Hi @lazarljubenovic, that errors are due to an `ng-katex` bug. You shouldn't import KaTeX fonts manually. I will fix it in a few days.

**Comment by garciparedes** [comment]
Hi! I showed that the bug only occurs in development mode. When the project is builded in production mode fonts are properly imported. I think the problem is in rollup config.

**Comment by garciparedes** [comment]
The problem was fixed by requiring explicitly import of `katex.css`. It can be read on [readme.md](https://github.com/garciparedes/ng-katex/blob/master/README.md)

**Comment by lazarljubenovic** [comment]
Works like a charm now. Thanks a lot!
