### ISSUE TITLE
Matrix brackets

### ISSUE THREAD

**Issue by filip-svoboda** [garciparedes/ng-katex#31]
Almost all matrices have wrong brackets

"c = \\begin{pmatrix} a & b \\\\ c & d\\\\  c & d\\end{pmatrix}"
![image](https://user-images.githubusercontent.com/35653184/35194334-83ae581c-feb2-11e7-9f9b-753258395fd4.png)
"c = \\begin{bmatrix} a & b \\\\ c & d\\\\  c & d\\end{bmatrix}"
![image](https://user-images.githubusercontent.com/35653184/35194349-a619e4ac-feb2-11e7-85a9-4cb7e32efa95.png)

**Comment by garciparedes** [comment]
Hi @filip-svoboda, I think the problem is due to your custom css code. You can proof those equations on demo app: https://garciparedes.me/ng-katex/

**Comment by filip-svoboda** [comment]
Hi @garciparedes, thank you, your demo app works fine, but I still cant make it work. I'm not using any css. Do you have any other ideas?

**Comment by garciparedes** [comment]
You should review the code of [demo](https://github.com/garciparedes/ng-katex/tree/master/demo) app. Note that since `ng-katex@1.0.0` you should import `katex.css` manually like the explanation in [readme](https://github.com/garciparedes/ng-katex#important).

**Comment by filip-svoboda** [comment]
Thank you very much, its working now, I really missed it :)
