### ISSUE TITLE
For some cases it doesn't support latex inputs which katex supports.

### ISSUE THREAD

**Issue by gaurav-bodhare** [garciparedes/ng-katex#329]
take the example of this latex-
'{\text{ In a solid }AB\text{ having the NaCl structure, }A\text{ atoms occupy the }}\text{ corners of the cubic unit cell. If all the face centred atoms along }\text{ one of the axes are removed, then the resultant stoichiometr. }\text{ of the solid is }{\text{ (a) }AB_2\text{ (b) }A_2B\quad\text{ (c) }A_4B_3\text{ (d) }A_3B_4}'

It is getting rendered on katex demo page( https://katex.org/ )  but not with ng-katex.

**Comment by gaurav-bodhare** [comment]
Probably katex new update is supporting these input. Maybe you have update dependency of katex.

**Comment by garciparedes** [comment]
Hi @gaurav-bodhare 
Check https://github.com/garciparedes/ng-katex/pull/298
