### ISSUE TITLE
Error with universal

### ISSUE THREAD

**Issue by lazarljubenovic** [garciparedes/ng-katex#34]
The SSR (universal) build of the application gives me the following error.

```
ERROR { Error: Uncaught (in promise): Error: StaticInjectorError[n]: 
  StaticInjectorError[n]: 
    NullInjectorError: No provider for n!
```

It's weird because universal usually errors out for usages of `document` at runtime. This is an AOT error, but the `ng serve --aot` works just fine for me. Seems like metadata or something has not been configured properly. A good place to start is to make sure the lib complies to [**Angular Package Format**](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit). The following two repos help with generating such a library: https://github.com/dherges/ng-packagr and https://github.com/steveblue/angular2-rollup.

**Comment by garciparedes** [comment]
Hi @lazarljubenovic! Can you explain me how to reproduce the Error? I've searched about it and found this issue: https://github.com/angular/angular/issues/20339 Maybe it can help you. 🙂

**Comment by lazarljubenovic** [comment]
Thanks for the reply and snooping around! I'll reproduce tonight or tomorrow morning in a clean CLI project.
