### ISSUE TITLE
New release version 1.1.0 - Can't find module 'ng-katex'

### ISSUE THREAD

**Issue by ReshmaKonepalli** [garciparedes/ng-katex#351]
New release doesn't work like ^1.0.3 as written in readme for demo app and my project as well. 
Installing or updating the version to 1.1.0 throws an error Can't find module 'ng-katex'.
Also, the structure of ng-katex under node modules is different. 

Can someone tell me how to work with new version?

Thanks!

**Comment by jamesnoonan** [comment]
I've had this issue as well and couldn't work out how to get it to work. I eventually tried out this command which worked for me: `npm install --save ng-katex@0.3.34`. There are probably newer versions you could install, but this seems to work fine for me.

**Comment by ReshmaKonepalli** [comment]
@jamesnoonan Thank you for the quick reply! 
Yes, it works fine for older versions. I've been using version@1.0.3 but now i want to upgrade it to new version since few symbols were not rendering in the older ones. 

And for new version the demo doesn't work as mentioned in readme. 

@garciparedes Can pl you let me know if there are any changes?

**Comment by ReshmaKonepalli** [comment]
@garciparedes I think the npm install for new version^1.1.0 doesn't install all the files. There are few missing files I added them from older version manually and now it works!

**Comment by ReshmaKonepalli** [comment]
Everything works fine with the new version ^1.1.1 as mentioned. Thanks!
