### ISSUE TITLE
Features described in current README do not match latest release

### ISSUE THREAD

**Issue by ahgentil** [garciparedes/ng-katex#505]
When will you make a new release that includes `ng-katex-html` and all that came after https://github.com/garciparedes/ng-katex/tree/109febdd505553a94e4341b648a0d8e248831b3f
?
Thanks

**Comment by garciparedes** [comment]
Hi @ahgentil!
You are right, the documentation on the `README.md` does not match the latest `ng-katex` version on `npm`. I'm planning to release a new version with those changes this weekend.

**Comment by garciparedes** [comment]
Hi @ahgentil, the new realease has been published right now 🙂 You can check the github release at: https://github.com/garciparedes/ng-katex/releases/tag/v1.3.0 and download it from npm.
