### ISSUE TITLE
Error: katex importing browsermodule

### ISSUE THREAD

**Issue by TapiwaJoel** [garciparedes/ng-katex#509]
**Describe the bug**
ng-katex giving error when importing it to NgModule

**Steps to reproduce the error**

- npm install ng-katet
- import into any module, (lazily loaded in my case)
- compile or build

**Error produced**
```
ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
```

**Comment by garciparedes** [comment]
Hi @TapiwaJoel ! You were right, there was a bug related with the `ng-katex` module dependencies. The referenced commit aims to fix your trouble. I've released the `ng-katex@1.3.1` with the patch right now.
