### ISSUE TITLE
Changing Delimiters

### ISSUE THREAD

**Issue by MusicDev33** [garciparedes/ng-katex#532]
As far I'm aware from reading the docs, there not really a good way to change the delimiters from the component.ts files. There's a way to do from the index.html, but I haven't found a way to get rid of the '$' '$' delimiters. An easy way to change the delimiters in the component.ts (passing in the options object) would be a good idea

**Comment by garciparedes** [comment]
Hi @MusicDev33 ! You were right. Currently, it's not possible to set custom delimiters on `ng-katex-paragraph`. Nevertheless, I think it would be an interesting feature. The responsability of the paragraph processing is left to `extract-math` (https://github.com/vberlier/extract-math) package. So before applying any change on `ng-katex` it's necessary to have that capability on `extract-math`.
