### ISSUE TITLE
[options] in ng-katex-paragraph

### ISSUE THREAD

**Issue by sergew92** [garciparedes/ng-katex#548]
Hello !

I'm using ng-katex in place of MathJax, thanks for the good work!

I'd have a suggestion : in ng-katex-paragraph directive, would it be possible to pass in [options], just like in ng-katex?

Thanks :)

Serge

**Comment by garciparedes** [comment]
Hi @sergew92! Right now it is not possible to set options on the `ng-katex-paragraph` directive. Nevertheless, it's an interesting feature! To do that, we need to modify the https://github.com/garciparedes/ng-katex/blob/master/src/ng-katex-paragraph.component.ts source file and allow to modify the `options` `Input` of `ng-katex` call. 🙂
