### ISSUE TITLE
ng-katex has problem with angular ivy

### ISSUE THREAD

**Issue by drlchen** [garciparedes/ng-katex#550]
**Describe the bug**

ng build succeed with ivy disabled but got following error when ivy is enabled.

Compiling @angular/flex-layout/grid : es2015 as esm2015
Compiling @angular/flex-layout : es2015 as esm2015
Compiling ng-katex : module as esm5

ERROR in node_modules/ng-katex/src/ng-katex.module.d.ts:1:22 - error TS-996002: Appears in the NgModule.imports of CalculateAreaModule, but could not be resolved to an NgModule class

I have refresh installed all packages (by delete the node-modules folder) but still cannot make it compile with ivy.

my system:
Angular CLI: 8.3.17
Node: 12.13.0
OS: win32 x64
Angular: 8.2.13

Please take a looks at this issue. Thank you !

**Comment by davidshen84** [comment]
Hi,

I got the same issue on Linux. I found turning off *aot* can work around this issue.
