### ISSUE TITLE
Make ng-katex work with Angular 9

### ISSUE THREAD

**Issue by sergew92** [garciparedes/ng-katex#584]
Hello !

Once again, I would like to thank you for the quality of your library, it is so helpful for my work.

I upgraded my project to Angular 9 yesterday. Unfortunately ng-katex is not working with this new version of Angular.

A minimal repro could be upgrading ng-katex demo app to Angular 9 : 
![image](https://user-images.githubusercontent.com/29337402/74087586-21236280-4a8e-11ea-9c62-fdd0b29506b0.png)

The only way to make it work is to disable Ivy compiler (new and enabled by default in Angular 9).
I tried to look at the issue here : https://github.com/angular/angular/issues?utf8=%E2%9C%93&q=is%3Aissue+ng6002

but unfortunately the issue seems to be highly technical...

By any chance, is there someone that could help make this great library work in Angular 9?

Thanks !

Serge

**Comment by john-melin** [comment]
Please merge in this feature. Im unable to upgrade to angular 9, only because of this dependency.

**Comment by garciparedes** [comment]
Hi! Since `ng-katex>=2.0.0` the ivy compilation should be resolved. Thanks to @mm716783 for his pull request!
