### ISSUE TITLE
Options: use the new 'output' option of Katex (>= v0.11.0)

### ISSUE THREAD

**Issue by schullq** [garciparedes/ng-katex#594]
Hello,

I'm using ng-katex on a little project I'm doing for fun. Very useful.

I realized that the options of ng-katex does not implement the 'output' options, newly introduced since Katex v.0.11.0. By default, Katex is rendering both in the same string.

I think it would be nice to have it, and avoid having the _MathML_ and the _HTML_ version printed every time.

**Comment by garciparedes** [comment]
Hi @schullq!

It's an interesting change, I'll merge your pull request. 🙂
