### ISSUE TITLE
Import Katex to make tree shaking possible

### ISSUE THREAD

**Issue by avelow** [garciparedes/ng-katex#652]
In https://katex.org/docs/node.html we can read :

KaTeX also provides an ECMAScript module:
```
import katex from 'katex/dist/katex.mjs'
````

In ng-katex, we import all the katex.js in the bundle that make it bigger
Using this import, we could make the bundle size smaller.

I will make a pull request for this

**Comment by avelow** [comment]
I misunderstood the KaTeX docs
The librabry is already imported using ECMAScript.

By the way, is there a difference in the generated bundle size if we use :
```
import { render, renderToString } from 'katex';
...
render(...)
renderToString(...)
```

instead of :
```
import * as katex from 'katex';
...
katex.render(...)
katex.renderToString(...)
```

**Comment by garciparedes** [comment]
Hi @avelow,

Thanks for your feedback! You're welcome to propose any pull request for this repository. I think you proposal is fine and, as you said, it'll produce an equal or less sized bundle due to the selective import. So if you submit the pull request, I'll approve it! 😉

**Comment by avelow** [comment]
Hi

I will do it tomorrow ! 

I may do another one to update the KatexOptions because there is some missing value like strict in the KatexOption declared in the library

**Comment by avelow** [comment]
I did the pull request #655

**Comment by garciparedes** [comment]
Okay! I'll review your merge request in the coming days and if everything is fine I'll proceed to merge it and generate a new release. Thank for your contribution @avelow!
