### ISSUE TITLE
Export the KatexService as part of the  Public API Surface of ng-katex

### ISSUE THREAD

**Issue by sshheye** [garciparedes/ng-katex#658]
**Is your feature request related to a problem? Please describe.**
Certain requirements needs the renderToString() and render() function currently in the KatexService <br/>
for instance a requirement to include katex in a text-editor will need the renderToString() function in the KatexService,
The current implementation hides the KatexService which prevents the use of the  renderToString().

**Describe the solution you'd like**
Export the KatexService as part of the  Public API Surface of ng-katex

**Describe alternatives you've considered**
I considered including the ng-katex project as a library in my current project and make the update from my local copy of the ng-katex

**Comment by garciparedes** [comment]
Hi @sshheye! I agree with you, if the implementation is already available I think is a good point to expose it on the public API, I'll accept your merge request. Thanks for your contribution!
