### ISSUE TITLE
Angular 9 evaluating 'input.split'

### ISSUE THREAD

**Issue by bekzatsa** [garciparedes/ng-katex#660]
Angular 9 has error when I use ng-katex-html, has error:
_`TypeError: undefined is not an object (evaluating 'input.split')`_

**Comment by garciparedes** [comment]
HI @bekzatsa, could you provide a more detailed explanation about the bug?

**Comment by bekzatsa** [comment]
[screenshot](https://ibb.co/0QzCzW3)

**Comment by bekzatsa** [comment]
<img width="524" alt="Снимок экрана 2021-01-12 в 15 18 42" src="https://user-images.githubusercontent.com/34629278/104310170-7917e400-54fd-11eb-9117-9046f0896e79.png">

**Comment by garciparedes** [comment]
Hi @bekzatsa, thanks for your help! Could you provide me a minimal example to reproduce it?

**Comment by bekzatsa** [comment]
`<p><span style="color: rgba(0, 0, 0, 0.65); font-family: 'Open Sans', sans-serif; font-size: 14px; letter-spacing: 0.2px; background-color: #ffffff;">You can write text, that contains expressions like this: $x ^ 2 + 5$ inside them.</span></p>`

`<ng-katex-html [html]="description"></ng-katex-html>`
When I use like that, then I get that error and display show nothing

Version: 
```
"katex": "^0.12.0",
"ng-katex": "^2.0.3"
```

**Comment by bekzatsa** [comment]
variable must be not empty, length must > 0
