### ISSUE TITLE
When using ng-katex-html the dom element is refreshed every angular lifecycle

### ISSUE THREAD

**Issue by Binarium-Dev** [garciparedes/ng-katex#662]
If you use `<ng-katex-html>` angular refreshes the DOM Element at every lifecycle.

This is quite inefficient and leads to UX problems (the text of the katex expression cannot be selected).

The reason for this is, that a getter is used in the template instead of a variable.

**Comment by garciparedes** [comment]
Hi @Binarium-Dev! Thanks for you your awesome explanation, and also for your code contribution. I'll review your changes and proceed to merge if everything is okay. Also, I want to generate a new release with these and another changes in a few days. 🙂
