### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by nikeee** [garciparedes/ng-katex#710]
Is this library compatible with Angular 13?

If not, can we help porting it?

**Comment by garciparedes** [comment]
Hi @nikeee, 

Currently I don't have enough time to update the library to be compatible with latest angular versions.

But if you want to do that, I'll review and integrate your PR and publish the corresponding release. 🙂

**Comment by nikeee** [comment]
I've updated the whole library to use angular 13:
https://github.com/garciparedes/ng-katex/compare/master...nikeee:angular-13?expand=1

However, this might result in the library being incompatible with angular < 13.

Also, tslint was removed from angular (without a replacement, one must configure to use eslint manually).

I see that the current version uses the v8 versions of the libraries. Should we keep this to be compatible with older versions?

**Comment by garciparedes** [comment]
Hi @nikeee! As I have not so much time to spend on this project I think it's preferable to keep the compatibility with older Angular versions, at least for the now.
